---
driver:
  name: vagrant
  require_chef_omnibus: 11.6.2

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
  - name: bento/centos-6.7

suites:
  - name: default
    run_list:
      - recipe[haproxy::default]
